### ISSUE TITLE
Motivation for this project

### ISSUE THREAD

**Issue by di** [akatrevorjay/tensorflow-auto-detect#1]
Hi! I'm a little curious about the motivation for this package, namely:

> Solves the absolute mess that is installing `tensorflow` from your package requirements.

Could you go into a bit more detail? This might be something I can help with.

**Comment by akatrevorjay** [comment]
@di Hi!

I have updated the README with info about this, would you mind taking a look and seeing if that answers this?

**Comment by akatrevorjay** [comment]
Personally, I would *love* if tensorflow did (or knew of) something that would avoid this hack

**Comment by di** [comment]
Thanks! That really helps. I've started a discussion about how to fix this at a larger scale, feel free to chime in if you have any thoughts: https://mail.python.org/mm3/archives/list/distutils-sig@python.org/thread/LXLF4YSC4WUZOYRX65DW7CESIX7UUBK5/

**Comment by akatrevorjay** [comment]
Fantastic! I'll keep watch of it, will chime in if I can be useful!
